package threads;

public class ResultTask extends Thread {
    public void run(){
        System.out.println("Result generated by:"+Thread.currentThread().getName());
    }
    public static void main(String[] args) {
        ResultTask t1=new ResultTask();
        t1.run(); // Normal executing->Always the main thread
        t1.start();// multi threading->T-0,T-1,.....so on
        //start() internally call run
        //thread cannot be started twice
    }
}
